/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISafeProxyFactory,
  ISafeProxyFactoryInterface,
} from "../../../../../src/contracts/interfaces/ISafe.sol/ISafeProxyFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_singleton",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "initializer",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "saltNonce",
        type: "uint256",
      },
    ],
    name: "createProxyWithNonce",
    outputs: [
      {
        internalType: "address",
        name: "proxy",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISafeProxyFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ISafeProxyFactoryInterface {
    return new Interface(_abi) as ISafeProxyFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISafeProxyFactory {
    return new Contract(address, _abi, runner) as unknown as ISafeProxyFactory;
  }
}
