/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iSafeSol from "./ISafe.sol";
export type { iSafeSol };
export type { IFinance } from "./IFinance";
export type { IRayanChainToken } from "./IRayanChainToken";
export type { IStaking } from "./IStaking";
