/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DAORegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACC_CONTROL"
      | "FINANCE"
      | "RAYAN_CHAIN_DAO"
      | "RAYAN_CHAIN_TOKEN"
      | "STAKING"
      | "USER_PROFILE"
      | "getAddress"
      | "owner"
      | "renounceOwnership"
      | "setAddress"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AddressSet" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ACC_CONTROL",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FINANCE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "RAYAN_CHAIN_DAO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RAYAN_CHAIN_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "STAKING", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "USER_PROFILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ACC_CONTROL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FINANCE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "RAYAN_CHAIN_DAO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RAYAN_CHAIN_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "STAKING", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "USER_PROFILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AddressSetEvent {
  export type InputTuple = [key: BytesLike, newAddress: AddressLike];
  export type OutputTuple = [key: string, newAddress: string];
  export interface OutputObject {
    key: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DAORegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DAORegistry;
  waitForDeployment(): Promise<this>;

  interface: DAORegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACC_CONTROL: TypedContractMethod<[], [string], "view">;

  FINANCE: TypedContractMethod<[], [string], "view">;

  RAYAN_CHAIN_DAO: TypedContractMethod<[], [string], "view">;

  RAYAN_CHAIN_TOKEN: TypedContractMethod<[], [string], "view">;

  STAKING: TypedContractMethod<[], [string], "view">;

  USER_PROFILE: TypedContractMethod<[], [string], "view">;

  getAddress: TypedContractMethod<[_key: BytesLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAddress: TypedContractMethod<
    [_key: BytesLike, _address: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACC_CONTROL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FINANCE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RAYAN_CHAIN_DAO"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RAYAN_CHAIN_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STAKING"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USER_PROFILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAddress"
  ): TypedContractMethod<
    [_key: BytesLike, _address: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AddressSet"
  ): TypedContractEvent<
    AddressSetEvent.InputTuple,
    AddressSetEvent.OutputTuple,
    AddressSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AddressSet(bytes32,address)": TypedContractEvent<
      AddressSetEvent.InputTuple,
      AddressSetEvent.OutputTuple,
      AddressSetEvent.OutputObject
    >;
    AddressSet: TypedContractEvent<
      AddressSetEvent.InputTuple,
      AddressSetEvent.OutputTuple,
      AddressSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
