/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FinanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "accControl"
      | "clientFeeBps"
      | "clientWallet"
      | "daoAddress"
      | "depositInvestment"
      | "finalizeInvestment"
      | "initialize"
      | "investments"
      | "investorBalances"
      | "owner"
      | "protocolFeeBps"
      | "protocolWallet"
      | "proxiableUUID"
      | "refundInvestment"
      | "registerInvestment"
      | "releaseFunds"
      | "releaseNextMilestone"
      | "renounceOwnership"
      | "setDaoAddress"
      | "setFeeConfiguration"
      | "setFeeWallets"
      | "token"
      | "transferOwnership"
      | "upgradeToAndCall"
      | "withdraw"
      | "withdrawTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DaoAddressSet"
      | "FeesDistributed"
      | "FundsDeposited"
      | "FundsReleased"
      | "Initialized"
      | "InvestmentCancelled"
      | "InvestmentDeposited"
      | "InvestmentRefunded"
      | "InvestmentRegistered"
      | "MilestoneReleased"
      | "NativeFundsWithdrawn"
      | "OwnershipTransferred"
      | "PlatformFeeTaken"
      | "TokenFundsWithdrawn"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accControl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clientFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clientWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "daoAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositInvestment",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeInvestment",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investorBalances",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundInvestment",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerInvestment",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseNextMilestone",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDaoAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeConfiguration",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeWallets",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokens",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "accControl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clientFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clientWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "daoAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investorBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseNextMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDaoAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokens",
    data: BytesLike
  ): Result;
}

export namespace DaoAddressSetEvent {
  export type InputTuple = [newDaoAddress: AddressLike];
  export type OutputTuple = [newDaoAddress: string];
  export interface OutputObject {
    newDaoAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesDistributedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    protocolFee: BigNumberish,
    clientFee: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    protocolFee: bigint,
    clientFee: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    protocolFee: bigint;
    clientFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentCancelledEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentDepositedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentRefundedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentRegisteredEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    recipient: AddressLike,
    totalAmount: BigNumberish,
    milestoneCount: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    recipient: string,
    totalAmount: bigint,
    milestoneCount: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    recipient: string;
    totalAmount: bigint;
    milestoneCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneReleasedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    amount: BigNumberish,
    milestoneNumber: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    amount: bigint,
    milestoneNumber: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    amount: bigint;
    milestoneNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeFundsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeTakenEvent {
  export type InputTuple = [proposalId: BigNumberish, feeAmount: BigNumberish];
  export type OutputTuple = [proposalId: bigint, feeAmount: bigint];
  export interface OutputObject {
    proposalId: bigint;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFundsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Finance extends BaseContract {
  connect(runner?: ContractRunner | null): Finance;
  waitForDeployment(): Promise<this>;

  interface: FinanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  accControl: TypedContractMethod<[], [string], "view">;

  clientFeeBps: TypedContractMethod<[], [bigint], "view">;

  clientWallet: TypedContractMethod<[], [string], "view">;

  daoAddress: TypedContractMethod<[], [string], "view">;

  depositInvestment: TypedContractMethod<
    [_proposalId: BigNumberish, _investor: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeInvestment: TypedContractMethod<
    [
      _proposalId: BigNumberish,
      _recipient: AddressLike,
      _totalRaised: BigNumberish,
      _milestoneCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [
      _initialOwner: AddressLike,
      _tokenAddress: AddressLike,
      _accControlAddress: AddressLike,
      _protocolWallet: AddressLike,
      _clientWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  investments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        recipient: string;
        totalAmount: bigint;
        releasedAmount: bigint;
        milestoneCount: bigint;
        currentMilestone: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  investorBalances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  protocolFeeBps: TypedContractMethod<[], [bigint], "view">;

  protocolWallet: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  refundInvestment: TypedContractMethod<
    [_proposalId: BigNumberish, _investor: AddressLike],
    [void],
    "nonpayable"
  >;

  registerInvestment: TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish
    ],
    [void],
    "view"
  >;

  releaseFunds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "view"
  >;

  releaseNextMilestone: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDaoAddress: TypedContractMethod<
    [_daoAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeConfiguration: TypedContractMethod<
    [_protocolFeeBps: BigNumberish, _clientFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeWallets: TypedContractMethod<
    [_protocol: AddressLike, _client: AddressLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawTokens: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accControl"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "clientFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "clientWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "daoAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositInvestment"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _investor: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeInvestment"
  ): TypedContractMethod<
    [
      _proposalId: BigNumberish,
      _recipient: AddressLike,
      _totalRaised: BigNumberish,
      _milestoneCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _initialOwner: AddressLike,
      _tokenAddress: AddressLike,
      _accControlAddress: AddressLike,
      _protocolWallet: AddressLike,
      _clientWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "investments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        recipient: string;
        totalAmount: bigint;
        releasedAmount: bigint;
        milestoneCount: bigint;
        currentMilestone: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "investorBalances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundInvestment"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _investor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerInvestment"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish
    ],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "releaseNextMilestone"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDaoAddress"
  ): TypedContractMethod<[_daoAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeConfiguration"
  ): TypedContractMethod<
    [_protocolFeeBps: BigNumberish, _clientFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeWallets"
  ): TypedContractMethod<
    [_protocol: AddressLike, _client: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawTokens"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DaoAddressSet"
  ): TypedContractEvent<
    DaoAddressSetEvent.InputTuple,
    DaoAddressSetEvent.OutputTuple,
    DaoAddressSetEvent.OutputObject
  >;
  getEvent(
    key: "FeesDistributed"
  ): TypedContractEvent<
    FeesDistributedEvent.InputTuple,
    FeesDistributedEvent.OutputTuple,
    FeesDistributedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentCancelled"
  ): TypedContractEvent<
    InvestmentCancelledEvent.InputTuple,
    InvestmentCancelledEvent.OutputTuple,
    InvestmentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentDeposited"
  ): TypedContractEvent<
    InvestmentDepositedEvent.InputTuple,
    InvestmentDepositedEvent.OutputTuple,
    InvestmentDepositedEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentRefunded"
  ): TypedContractEvent<
    InvestmentRefundedEvent.InputTuple,
    InvestmentRefundedEvent.OutputTuple,
    InvestmentRefundedEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentRegistered"
  ): TypedContractEvent<
    InvestmentRegisteredEvent.InputTuple,
    InvestmentRegisteredEvent.OutputTuple,
    InvestmentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneReleased"
  ): TypedContractEvent<
    MilestoneReleasedEvent.InputTuple,
    MilestoneReleasedEvent.OutputTuple,
    MilestoneReleasedEvent.OutputObject
  >;
  getEvent(
    key: "NativeFundsWithdrawn"
  ): TypedContractEvent<
    NativeFundsWithdrawnEvent.InputTuple,
    NativeFundsWithdrawnEvent.OutputTuple,
    NativeFundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeTaken"
  ): TypedContractEvent<
    PlatformFeeTakenEvent.InputTuple,
    PlatformFeeTakenEvent.OutputTuple,
    PlatformFeeTakenEvent.OutputObject
  >;
  getEvent(
    key: "TokenFundsWithdrawn"
  ): TypedContractEvent<
    TokenFundsWithdrawnEvent.InputTuple,
    TokenFundsWithdrawnEvent.OutputTuple,
    TokenFundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "DaoAddressSet(address)": TypedContractEvent<
      DaoAddressSetEvent.InputTuple,
      DaoAddressSetEvent.OutputTuple,
      DaoAddressSetEvent.OutputObject
    >;
    DaoAddressSet: TypedContractEvent<
      DaoAddressSetEvent.InputTuple,
      DaoAddressSetEvent.OutputTuple,
      DaoAddressSetEvent.OutputObject
    >;

    "FeesDistributed(uint256,uint256,uint256)": TypedContractEvent<
      FeesDistributedEvent.InputTuple,
      FeesDistributedEvent.OutputTuple,
      FeesDistributedEvent.OutputObject
    >;
    FeesDistributed: TypedContractEvent<
      FeesDistributedEvent.InputTuple,
      FeesDistributedEvent.OutputTuple,
      FeesDistributedEvent.OutputObject
    >;

    "FundsDeposited(address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "FundsReleased(address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "InvestmentCancelled(uint256)": TypedContractEvent<
      InvestmentCancelledEvent.InputTuple,
      InvestmentCancelledEvent.OutputTuple,
      InvestmentCancelledEvent.OutputObject
    >;
    InvestmentCancelled: TypedContractEvent<
      InvestmentCancelledEvent.InputTuple,
      InvestmentCancelledEvent.OutputTuple,
      InvestmentCancelledEvent.OutputObject
    >;

    "InvestmentDeposited(uint256,address,uint256)": TypedContractEvent<
      InvestmentDepositedEvent.InputTuple,
      InvestmentDepositedEvent.OutputTuple,
      InvestmentDepositedEvent.OutputObject
    >;
    InvestmentDeposited: TypedContractEvent<
      InvestmentDepositedEvent.InputTuple,
      InvestmentDepositedEvent.OutputTuple,
      InvestmentDepositedEvent.OutputObject
    >;

    "InvestmentRefunded(uint256,address,uint256)": TypedContractEvent<
      InvestmentRefundedEvent.InputTuple,
      InvestmentRefundedEvent.OutputTuple,
      InvestmentRefundedEvent.OutputObject
    >;
    InvestmentRefunded: TypedContractEvent<
      InvestmentRefundedEvent.InputTuple,
      InvestmentRefundedEvent.OutputTuple,
      InvestmentRefundedEvent.OutputObject
    >;

    "InvestmentRegistered(uint256,address,uint256,uint8)": TypedContractEvent<
      InvestmentRegisteredEvent.InputTuple,
      InvestmentRegisteredEvent.OutputTuple,
      InvestmentRegisteredEvent.OutputObject
    >;
    InvestmentRegistered: TypedContractEvent<
      InvestmentRegisteredEvent.InputTuple,
      InvestmentRegisteredEvent.OutputTuple,
      InvestmentRegisteredEvent.OutputObject
    >;

    "MilestoneReleased(uint256,uint256,uint8)": TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;
    MilestoneReleased: TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;

    "NativeFundsWithdrawn(address,uint256)": TypedContractEvent<
      NativeFundsWithdrawnEvent.InputTuple,
      NativeFundsWithdrawnEvent.OutputTuple,
      NativeFundsWithdrawnEvent.OutputObject
    >;
    NativeFundsWithdrawn: TypedContractEvent<
      NativeFundsWithdrawnEvent.InputTuple,
      NativeFundsWithdrawnEvent.OutputTuple,
      NativeFundsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeeTaken(uint256,uint256)": TypedContractEvent<
      PlatformFeeTakenEvent.InputTuple,
      PlatformFeeTakenEvent.OutputTuple,
      PlatformFeeTakenEvent.OutputObject
    >;
    PlatformFeeTaken: TypedContractEvent<
      PlatformFeeTakenEvent.InputTuple,
      PlatformFeeTakenEvent.OutputTuple,
      PlatformFeeTakenEvent.OutputObject
    >;

    "TokenFundsWithdrawn(address,uint256)": TypedContractEvent<
      TokenFundsWithdrawnEvent.InputTuple,
      TokenFundsWithdrawnEvent.OutputTuple,
      TokenFundsWithdrawnEvent.OutputObject
    >;
    TokenFundsWithdrawn: TypedContractEvent<
      TokenFundsWithdrawnEvent.InputTuple,
      TokenFundsWithdrawnEvent.OutputTuple,
      TokenFundsWithdrawnEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
